### ISSUE TITLE
Stock Information - Add/Remove a Comparison Ticker

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#11]
- [ ] Once you add a comparison ticker, its extremely challenging to remove it, the only way to get rid of a comparison ticker is to add a different one (or enter something that's not a ticker which will remove it)
- [ ] When you add a comparison ticker, you must hit the + button, hitting return/enter will not add the ticker symbol

![stock_information_comparison_tickers](https://cloud.githubusercontent.com/assets/18052292/14889198/c2965cfc-0d2b-11e6-91b6-260ca14b1b01.gif)

**Comment by DharmeshRana** [comment]
Fixed - https://www.snl.com/IRW/Stock/4363272/preview

**Comment by stevenaquinn** [comment]
I think this fix has made it less intuitive, and we've introduced an issue as well.
- [x] "ADD COMPARISON TICKER" should only disappear when selected (it is currently blank)
- [ ] When a ticker is typed, enter/return should add it to the chart.
- [ ]  Its still unintuitive to remove a comparison ticker, for this solution maybe we should add a clear tickers button so it goes back to being just MC on the chart? @esea48 could you give your opinion on this one?
- [x] Currently, when you add a ticker, for example GOOG, then hit add with a blank ticker line, it removes MC instead of GOOG. MC should never be removed, it should be the added ticker that is removed.

**Comment by DharmeshRana** [comment]
Ellen,

Let's discuss this. It looks like there's some confusion with the functionality.

**Comment by DharmeshRana** [comment]
Let me provide you my view points here.

Point #1 looks fine. Kindly check.

I am asking my design team if this is possible.

I got your point and agreed but this would be a global enhancement. I will forward this to our developer for next cycle update.

I have added GOOG and removed but that hasn't removed MC.

**Comment by stevenaquinn** [comment]
First issue seems to be much better to me. I've reviewed the chart again and have reanalyzed the remaining issues, as it looks like refactors have changed the nature of the chart
- [ ] When a ticker is typed, enter/return should add it to the chart.
- [ ] Reset button in the Overlays drawer seems to change the vertical axis from percent change to price, and removes all of the options selected in the Overlays drawer, but will not remove the comparison ticker.  I can't find a place to remove the comparison ticker (Only to grey it out by clicking on it at the bottom of the chart.) 

The following 2 need input from @esea48 
- [ ] Aware that MC has only been trading since April '14 is it okay that comparison tickers don't run back further on a 3Y/5Y chart? as discussed in #10  @esea48 
- [ ] Drawers don't function like normal drawers, I'm unsure of the aim on functionality here, but the way the hover states are used to keep the drawers open/close them doesn't feel intuitive to me @esea48 perhaps we should take a look at this together and we can decide our functionality aim so I can better direct fixes. Ref #10

**Comment by DharmeshRana** [comment]
Functionality has been added for "Add Comparison Ticker". If you add ticker and hit enter, it will be added to the chart. Same way, if you remove the ticker and hit enter, it will be removed from the chart.
