### ISSUE TITLE
Corp Governance - Items missing/mispositioned

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#12]
- [x] We're missing the "Executive Officers & Directors" header and rule
- [x] "Bio" was set higher on wireframes and in other parts of the site
- [x] Bio had an arrow in the wireframe but now has a + instead

(wireframe is on right for comparison)
![corp_gov_edits](https://cloud.githubusercontent.com/assets/18052292/14889779/2602ae42-0d2e-11e6-9d9b-c541f81f9767.png)

**Comment by esea48** [comment]
@dharmeshrana - please review these edits. The two items he mentioned we must implement.

are you ok with this?

**Comment by stevenaquinn** [comment]
The listed issues have been fixed. On wireframe Bios are coming up as an internal page, but on live site they operate like drawers. @esea48 if your okay with this we can close this ticket.

![corp_gov_bio_internal_page](https://cloud.githubusercontent.com/assets/18052292/15258810/967cc5ba-191b-11e6-89ca-b7fa34909022.png)
