### ISSUE TITLE
Events & Presentations - Questions

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#13]
Are we missing content for this page? There is no section for Presentations, nor Upcoming Events.

If not, should we call it Events & Presentations with no upcoming events and no presentations?

![events_presentations_questions](https://cloud.githubusercontent.com/assets/18052292/14890722/b8d29964-0d31-11e6-85a2-cf4e96853d3a.png)

**Comment by DharmeshRana** [comment]
This has been fixed. Kindly re-check.
