### ISSUE TITLE
Press Release - Internal Pages not popups

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#14]
On the Press Release Page wireframe/reference, and on our section of the site, internal pages are a pop up white box with X's.  Here they are internal pages instead.

![press_releases_internal_pages](https://cloud.githubusercontent.com/assets/18052292/14892015/11a07174-0d37-11e6-8319-21669cc51a66.gif)

**Comment by esea48** [comment]
dup of #35.
