### ISSUE TITLE
Analyst Coverage - Missing Bold/Rule

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#15]
Firm and Analyst are column headers and should be bold and have a rule running across the page. Also, below the footer we have grey space (should likely be black if the browser is tall enough that there is space below footer).

![analyst_coverage_styling](https://cloud.githubusercontent.com/assets/18052292/14892319/4b29c782-0d38-11e6-9861-59f15fe8a760.png)

**Comment by DharmeshRana** [comment]
This has already been fixed and available in the preview mode.

https://www.snl.com/IRW/CustomPage/preview/4363272/Index?KeyGenPage=210335

Thanks!
