### ISSUE TITLE
Font comparison - prototype and current build

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#17]
See the two screenshots below, first the prototype (which is an image, with font therefore changing size as the page size is adjusted), followed by the current build in IE11.

Is there some sort of difference in font, overall, between the two versions? It appears that the the main text font is possibly a heavier weight than the dev build. To make this comparison clear, I've actually made the prototype image just a bit smaller than the current page -- notice how in the comparison below, even when the prototype font is smaller in point size, it still appears to be more bold, i.e. of a heavier weight.

It appears that on other pages there are other discrepancies between the current build and the prototype. Should we go through and document every instance where it seems that the current build differs from the prototype in terms of font styling, or do we assume that the current build is correct and approved.?

**Prototype (page and font size reduced slightly):**

![font prototype homepage](https://cloud.githubusercontent.com/assets/7999085/14892727/2c8a637a-0d3a-11e6-924e-9d486ce0e881.png)

---

.
.
.
.

**Current build dev build (from IE11 but identical in other browsers):**

![font homepage ie11](https://cloud.githubusercontent.com/assets/7999085/14892733/34078948-0d3a-11e6-82dc-8789e8023ca7.png)

**Comment by DharmeshRana** [comment]
Ellen,

Would you mind commenting on this? In my sense, font looks good on the preview page?

Thanks!

**Comment by esea48** [comment]
this is fine
