### ISSUE TITLE
Stock Information - drawers cannot be closed by clicking outside of chart area (desktop browsers)

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#20]
In all desktop browsers, when either of the main Stock Information chart drawers (Overlays, Options) is opened, the only way to close the drawer is to click the top of the drawer again -- you cannot click outside the chart area to close the drawer, which seems intuitive.

(GIF below from IE10, but identical experience on all desktop browsers.) 

![ie10 drawer open close](https://cloud.githubusercontent.com/assets/7999085/14899883/20b0ca72-0d5c-11e6-95f2-930661180270.gif)

**Comment by DharmeshRana** [comment]
Fixed - https://www.snl.com/IRW/Stock/4363272/preview
