### ISSUE TITLE
Stock Information - overlap of drawers and timelength select buttons (desktop browsers)

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#21]
In all desktop browsers, when making chart selections involving both drawers and the timelength selector buttons (1D, 1W, etc.), the buttons can overlap the left or right side of the drawers in a buggy-looking way.

(GIFs below from IE10, but identical experience on all desktop browsers.) 

![ie10 highlight drawer overlap](https://cloud.githubusercontent.com/assets/7999085/14899264/41c7792a-0d59-11e6-9c40-0e8c97d5dd0f.gif)

![ie10 highlight drawer overlap 2](https://cloud.githubusercontent.com/assets/7999085/14899452/08393cd8-0d5a-11e6-9c84-cd9f3d5098f9.gif)

**Comment by DharmeshRana** [comment]
Fixed -  https://www.snl.com/IRW/Stock/4363272/preview
