### ISSUE TITLE
Phones -  Corporate Overview and Events & Presentations: slideshow does not fit in window (portrait orientation)

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#26]
On all phones (iPhone 5 and 6, Android phones), in **portrait orientation**, the slideshow on both the Corporate Overview and Events & Presentations pages do not fit in the window. 

(Screenshots below from iPhone 6, but identical in iPhone 5 and Android phones.)

![image](https://cloud.githubusercontent.com/assets/7999085/14930661/b052caea-0e33-11e6-9752-d37bec9a4495.jpg)
![image](https://cloud.githubusercontent.com/assets/7999085/14930663/b0598f74-0e33-11e6-926b-2b2249f63894.jpg)

**Comment by rmcneilladdison** [comment]
As discussed a couple days ago, this is still uncorrected.

**Comment by DharmeshRana** [comment]
This should be fixed from the slideshare plug-in who handles it.
