### ISSUE TITLE
IE9 - Financial Reports & SEC Filings: Search - "Enter search term" text does not appear

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#31]
In IE9, on the Financial Reports & SEC Filings page, the search field next to the search icon is missing the "Enter search term" text that appears in all other browsers. See screenshot below:

![ie9 fin reports search](https://cloud.githubusercontent.com/assets/7999085/14931022/410e233e-0e36-11e6-961e-cefd61897507.png)

**Comment by DharmeshRana** [comment]
Fixed
