### ISSUE TITLE
FAQ - link missing for Moelis & Company's auditor (Global)

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#32]
In the 11th FAQ on the FAQ page ("Who are Moelis & Company's auditors?"), the answer -- "Moelis & Company is audited by Deloitte & Touche LLP" -- does not include a hyperlink for Deloitte & Touche. In other FAQs, however (for example, those that refer to Moelis's transfer agent, Computershare), external companies are hyperlinked. Should Deloitte & Touche be hyperlinked here?

**Comment by DharmeshRana** [comment]
The link isn't appearing on the current IR site as well. Please check with Margot and I will be happy to update this.
