### ISSUE TITLE
upload new photos for Corporate Governance page

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#33]
See zip for new photos
[SNL-headshots[1].zip](https://github.com/esea48/MoelisIR/files/245528/SNL-headshots.1.zip)

**Comment by DharmeshRana** [comment]
New Images have been added - https://www.snl.com/IRW/OD/4363272/preview

Ken Moelis image looks different in size. Can you please provide the same image with the size 640 X 640?

Thanks!
