### ISSUE TITLE
Events and presentations - please see comp pdf for correct layout.

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#34]
currently:
![uploads/f82c8852-3dbd-4097-bfea-42096f51271d/screencapture-www-snl-com-IRW-event-4363272-preview-1462209065985.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff82c8852-3dbd-4097-bfea-42096f51271d%2Fscreencapture-www-snl-com-IRW-event-4363272-preview-1462209065985.png)

should be:

![uploads/1d8e197c-08f2-4e44-bdb0-7030de2b24ea/Screen Shot 2016-05-02 at 1.17.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1d8e197c-08f2-4e44-bdb0-7030de2b24ea%2FScreen+Shot+2016-05-02+at+1.17.47+PM.png)

**Comment by stevenaquinn** [comment]
Some issues have been addressed but others still remain.
- [ ] Presentation controls still visible
- [ ] Still Missing "Upcoming Events"
- [ ] Font for event titles looks like a medium or bold (darker than example)
- [ ] Webcast link is transposed, contain a colon, are not all caps, and are in a different font than example
- [ ] Phone number font is grey in the example, okay black here?

![events_presentations_issues](https://cloud.githubusercontent.com/assets/18052292/15259370/ef7be440-191e-11e6-88b8-89dc1fefe558.png)

**Comment by DharmeshRana** [comment]
1) Presentation controls are coming from plug-ins. Who is managing the plug-ins, they need to update it.
2) There's no upcoming events and that's the reason you are not seeing this section.
3) Font fixed
4) Fixed
5) Fixed
