### ISSUE TITLE
Corp Overview - Webcast Links Question

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#37]
Current way the link works is via the blue underlined portion. Wouldn't it be most intuitive to also include the Webcast Icon as a clickable/touchable part of the link?

![webcast_icon_link](https://cloud.githubusercontent.com/assets/18052292/14990301/faf742d0-1129-11e6-9567-5e572f14ba78.png)

**Comment by DharmeshRana** [comment]
Make sense. Fixed - https://www.snl.com/irw/CorporateProfile/4363272/preview
