### ISSUE TITLE
Corp Overview - Add Space in Sidebar

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#38]
Should have a space after Change before parens for consistency & readability to match market cap.

![corporate_overview_space_for_consistency](https://cloud.githubusercontent.com/assets/18052292/14990543/100e33ee-112b-11e6-97ee-d3193fcd6e99.png)

**Comment by stevenaquinn** [comment]
The spacing before parens is fixed. Thanks. Additionally, I noticed an inconsistency on this page in the spacing after the colon in "NYSE: MC". See examples. Should we make them consistent?

![nysemc spacing after colon](https://cloud.githubusercontent.com/assets/18052292/15260031/79875554-1922-11e6-8872-36c3f2760907.png)

**Comment by esea48** [comment]
@stevenaquinn - yes. @DharmeshRana - can you add the space in the paragraph?

**Comment by DharmeshRana** [comment]
Paragraph fixed. Space added.
