### ISSUE TITLE
iPhone - FAQ - Font Sizing

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#41]
Happening on iPhone 5 + 6. Only appears to be an issue in landscape, some "answers" appear in normal font, but some appear to scale up in landscape. Whether we want them all to render large, or if only 

Following is a list of the questions that appear large:
- Who is Moelis & Company’s transfer agent and how do I contact them?
- How do I change my address for my dividend checks, annual report to shareholders and other company information?
- How do I transfer Moelis & Company shares from one shareholder to another?
- When does Moelis & Company report earnings?
- How do I obtain copies of Moelis & Company’s financial reports?
- How do I contact Moelis & Company Investor Relations?
- How do I sign up for email alerts from Moelis & Company?

![faq_font_sizing](https://cloud.githubusercontent.com/assets/18052292/14996326/634dde1c-1147-11e6-86f9-cfa214ea0093.gif)

**Comment by rmcneilladdison** [comment]
Verified fixed, thank you. Closing this completed issue.
