### ISSUE TITLE
Corporate Governance - order of appearance changes

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#43]
- [ ] In Navid’s bio, missing a space between School and the ( in very last sentence. Magna cum laude should be italicized in very last sentence. 
- [ ] Change order of executive officers & directors to: Ken Moelis, Navid Mahmoodzadegan, Jeff Raich, Eric Cantor, Rick Leaman, and then everyone else as listed from John Allison down

**Comment by DharmeshRana** [comment]
I am not able to find School and the together.

Both the other concerns fixed. https://www.snl.com/irw/od/4363272/preview

**Comment by esea48** [comment]
@DharmeshRana  Hi - can you please italicized magna cum laude (I've highlighted below" 
![screen shot 2016-05-25 at 1 24 56 pm](https://cloud.githubusercontent.com/assets/10871398/15549695/d1ef72e6-227b-11e6-8220-d5cb00531f98.png)

**Comment by DharmeshRana** [comment]
This has already been completed. Do you see any issue? https://www.snl.com/irw/od/4363272/preview

Per my view, it's not easily reflected because of different font.

**Comment by esea48** [comment]
wait dharmesh -... so you can't make a font _italicize_?

**Comment by DharmeshRana** [comment]
The requested text is appearing in italicize now.
