### ISSUE TITLE
Financial Reports & SEC Filings - edits still missing

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#44]
- All Filings section is missing expand/collapse button – still missing
- Please hide “abstract” as per design – use the same function “more function” as the current site
- Add filter for the types of documents listed on this page –  Still confused about the filtering here…can we not just move the filter to below all filings?

**Comment by DharmeshRana** [comment]
There's reason we shouldn't need to move filter under All filings as it also filter the Highlights section as well. I hope it make sense but let me know if you still have any question.

I will ask my design team to fix the first 2 points.

**Comment by DharmeshRana** [comment]
Fixed first 2 points
