### ISSUE TITLE
FAQ - missing design elements

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#47]
- Links in FAQs need to go to new IR pages – almost there, missing a few design elements.

Link to FAQ style on main site: 
http://dev1.moelis.addison.com/careers/

SEE COMP:

![screen shot 2016-05-16 at 2 27 15 pm](https://cloud.githubusercontent.com/assets/10871398/15299376/14f4cdcc-1b72-11e6-87e4-8a751954da22.png)

**Comment by esea48** [comment]
@DharmeshRana where are we on this?

**Comment by DharmeshRana** [comment]
Fixed. Kindly review.
