### ISSUE TITLE
iPhone 5 - Corporate Overview: NYSE ticker information - Market Cap "($M)" out of place

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#48]
On the iPhone 5, with its smaller display window, the "($M)" characters that _should_ sit to the right of the words "Market Cap" under NYSE: MC in the ticker area -- are actually sitting on the next line down (below the word "Market"). Occurs in **portrait orientation only**; landscape is fine. See screenshot below:
![image](https://cloud.githubusercontent.com/assets/7999085/15303377/79374ebe-1b85-11e6-88d3-7cc59c3f75ce.jpg)

**Comment by DharmeshRana** [comment]
Fixed!
