### ISSUE TITLE
Android - Stock Information: sub-menu dropdowns not selectable

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#49]
On Android -- phone and tablet -- the submenu dropdowns under OVERLAYS and OPTIONS are not selectable.

You can open OVERLAYS or OPTIONS, but then, when you try to open a sub-menu -- for example, "Indexes" -- nothing happens (other than the entire menu just closing back up).

**Comment by DharmeshRana** [comment]
Fixed
