### ISSUE TITLE
NEW BIOS FOR CORPORATE GOVERNANCE SECTION

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#50]
Please put new bios for the following people below.

**Navid Mahmoodzadegan:**
Navid Mahmoodzadegan is a Co‑Founder and has served as Co‑President since September 2015 and as a Managing Director of our Company since 2007. Mr. Mahmoodzadegan has been a director since April 2014. Prior to founding our Company, Mr. Mahmoodzadegan worked at UBS from 2001 to 2007, where he was most recently Global Head of Media Investment Banking. Before joining UBS, Mr. Mahmoodzadegan was an investment banker at Donaldson, Lufkin & Jenrette from 1995 to 2001. He began his career as an attorney with Irell & Manella. Mr. Mahmoodzadegan is a member of the Harvard Law School Dean’s Leadership Council of Southern California. He holds an A.B. with Highest Distinction from the University of Michigan (Phi Beta Kappa) and a J.D. from Harvard Law School, magna cum laude. Mr. Mahmoodzadegan serves on the Carlthorp School Board of Trustees and the National Board of Directors of Jumpstart.

**Jeff Raich:**
Jeffrey Raich is a Co‑Founder and has served as Co‑President since September 2015 and Managing Director and Head of Mergers and Acquisitions of our Company since 2007. Mr. Raich has been a director since April 2014. Prior to founding our Company, Mr. Raich worked at UBS from 2001 to 2007 where he was most recently Joint Global Head of Mergers and Acquisitions. Prior to joining UBS, Mr. Raich was a Managing Director and Head of West Coast Mergers and Acquisitions at Donaldson, Lufkin & Jenrette, where he worked from 1996 to 2000. He began his career as an investment banker with PaineWebber in 1989. Mr. Raich is a member of the McIntire School of Commerce Advisory Board at the University of Virginia and a Board Member of the UCLA Health System. Mr. Raich also serves on the Marlborough School Board of Trustees. He holds a B.S. in Commerce with Distinction from the McIntire School of Commerce at the University of Virginia.

**Rick Leaman:**
J. Richard Leaman III has served as Vice Chairman of our Company since September 2015 and previously served as Managing Partner since 2012. Mr. Leaman has been a director since April 2014. Prior to joining our Company in 2010 as a Managing Director, Mr. Leaman worked at UBS from 1997 to 2010, most recently as Chairman of UBS Investment Bank’s Investment Banking Division and previously as Global Head of Investment Banking, Joint Global Head of Investment Banking, Global Head of Mergers and Acquisitions, as well as Co‑Head of Healthcare Banking at Dillon, Read & Co. Inc., which was acquired by UBS in 1997. Before joining Dillon, Read & Co. Inc., Mr. Leaman was an investment banker at Smith Barney, Harris Upham & Co. Incorporated from 1986 to 1992. Mr. Leaman is a member of the Board of Visitors for the Fuqua School of Business. Mr. Leaman holds a B.A. from Duke University and an M.B.A. from the Fuqua School of Business at Duke University.

**John Allison:**
John A. Allison IV has been a director since October 2015. Mr. Allison is Executive in Residence at Wake Forest School of Business and Chairman of the Executive Advisory Council of the Cato Institute’s Center for Monetary and Financial Alternatives, and a member of the Cato Institute’s Board of Directors. Mr. Allison was president and CEO of the Cato Institute from October 2012 to April 2015. Mr. Allison served as the Chief Executive Officer of BB&T Corporation from 1989 to 2008. Mr. Allison was also a director of BB&T Corporation from 1986 to 2014, serving as Chairman from 1989 to 2008, and a Branch Bank & Trust Company director from 1986 to 2008 and 2013 to 2014. Mr. Allison served as Chairman and Chief Executive Officer of Branch Bank & Trust Company from 1989 to 2008. He also served as a Distinguished Professor of Practice on the faculty of the Wake Forest University Schools of Business from 2009 to 2012. Mr. Allison is a Phi Beta Kappa graduate of the University of North Carolina—Chapel Hill. He received his master’s degree in management from Duke University, and is also a graduate of the Stonier Graduate School of Banking.

**Yvonne Greenstreet:**
Dr. Yvonne Greenstreet has been a director since February 2015. Dr. Greenstreet served as Senior Vice President and Head of Medicines Development for Pfizer from 2011 to 2013 and was a member of the Specialty Business global executive team. Prior to Pfizer, Dr. Greenstreet was at GlaxoSmithKline from 1992 to 2010, most recently as Senior Vice President and Chief of Strategy for Research and Development and a member of the corporate portfolio management board. Dr. Greenstreet is a member of the Board of Directors of Pacira Pharmaceuticals, a pharmaceutical company that develops products for postsurgical pain control, a member of the Board of Directors of Advanced Accelerator Applications, a radiopharmaceutical company that develops diagnostic and therapeutic products, and a member of the Board of Directors of Indivior, a pharmaceutical company that develops products to treat addiction. She is also a member of the Scientific Advisory Committee of the Bill and Melinda Gates Foundation. Dr. Greenstreet holds a Bachelor of Medicine, Bachelor of Surgery from the University of Leeds, United Kingdom, and an M.B.A. from INSEAD, France.

**Kenneth Shropshire:**
Kenneth L. Shropshire has been a director since July 2014. Mr. Shropshire is the David W. Hauck Professor at the Wharton School at the University of Pennsylvania and the Faculty Director of its Wharton Sports Business Initiative. Mr. Shropshire joined the Wharton faculty in 1986 specializing in sports business and law and served as Chairman of the Wharton School’s Legal Studies and Business Ethics department from 2000 to 2005. Mr. Shropshire is Special Counsel to the global law firm Duane Morris LLP where he practices corporate law with a concentration in sports and business law. He is also a consultant to the owner of the Miami Dolphins and a consultant to the National Football League, where he assists the organization in expanding its player development and social impact program, and he currently leads the research efforts of the Major League Baseball On‑Field Diversity Task Force. His consulting roles have also included work for the NCAA, the NFL Players Association and USA Track and Field, and he was an executive on the organizing committee for the 1984 Los Angeles Olympic Games. Mr. Shropshire was previously a member of the board of directors of Peace Players International and Valley Green Bank in Philadelphia and a trustee of the Women’s Sports Foundation. He is a former president of the Sports Lawyers Association, the largest such organization in the world, and Program Chair of the ABA Forum Committee, Sports Law Section. Mr. Shropshire is the author of numerous books and articles on the business of sports. He holds an A.B. in economics from Stanford University and a J.D. from Columbia Law School.

**Joe Simon:**
Joseph Simon has served as our Chief Financial Officer since 2010. Prior to joining our Company, Mr. Simon served as Chief Financial Officer of Financial Security Assurance from 2002 to 2010. Prior to joining Financial Security Assurance, Mr. Simon served as Chief Financial Officer of IntraLinks and TENTV.com from 2000 to 2002. Prior to that, Mr. Simon worked at Cantor Fitzgerald where he served as Chief Financial Officer, Global Controller and Global Head of Operations from 1993 to 1999. Before joining Cantor Fitzgerald, Mr. Simon was a Fixed Income Product and Legal Entity Controller at Morgan Stanley from 1986 to 1993. He began his career at Price Waterhouse from 1983 to 1986. Mr. Simon holds a B.S. from Cornell University and an M.B.A. from The University of Michigan. He is a Certified Public Accountant.

**Comment by esea48** [comment]
@stevenaquinn - can you ask yoris or jessica to check this ? do a comparison read on the site

**Comment by stevenaquinn** [comment]
Have done a comparison read, and it all looks good! Closing ticket, thank you!
