### ISSUE TITLE
Safari / iPad - Stock Information: overlap of dollar figures and category caption

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#52]
In the iPad -- both portrait and landscape orientation -- the initial dollar figures are overlapping some of the category captions, such as "LAST", "CHANGE", "TODAY'S HIGH", etc.  (Not happening in Android tablet, or phones in either operating system -- iPad only.  See first two screenshots below, portrait followed by landscape.)

Seems that the issue may be caused by the Safari browser. On Safari browser in Mac, when screen size is adjusted to tablet breakpoint, overlap happens, _but in only one of the categories_ (the first "CHANGE"). See third and fourth screenshots below -- in the third, just before the breakpoint is reached, the overlap is not happening; in the fourth, the breakpoint is passed, and the overlap is occurring. 

Screenshot 1:

![image](https://cloud.githubusercontent.com/assets/7999085/15341384/4c449240-1c5c-11e6-81b4-bdedc4960bbe.jpg)
.
.
.
.

Screenshot 2:

![image](https://cloud.githubusercontent.com/assets/7999085/15341385/4c492db4-1c5c-11e6-9e70-045a28758c1f.jpg)
.
.
.
.

Screenshot 3 (Safari/Mac -- just before breakpoint):

![screen shot 2016-05-17 at 6 02 35 pm](https://cloud.githubusercontent.com/assets/7999085/15341436/a5a406fe-1c5c-11e6-9419-9a23b8799dd1.png)

.
.
.
.

Screenshot 4 (Safari/Mac -- just after breakpoint):

![screen shot 2016-05-17 at 6 03 18 pm](https://cloud.githubusercontent.com/assets/7999085/15341440/ab1018e4-1c5c-11e6-8d35-07fce3ba3a08.png)

**Comment by DharmeshRana** [comment]
Fixed
