### ISSUE TITLE
Press Releases: formatting clean-up needed

### ISSUE THREAD

**Issue by rmcneilladdison** [esea48/MoelisIR#53]
The formatting of the individual press releases is jumbled. Data that looks like it should appear on separate lines is running together without break; points in the text that would seem to call for a paragraph or hard return are instead just jumbled together with preceding text; words/ names/ numbers/ phone extensions and email addresses run together at various places where a line break or at least a space should separate.

See blocks of text below, copied from first press release in section. Formatting here should follow main site, News section.

For example, here are the last four paragraphs from what is currently the first press release on the page: 

Adjusted ProForma

Revenues $ 99,412 $ - $ 99,412   Expenses Compensation and benefits 55,393 (1,460 ) (a) 53,933 Non-compensation expenses   22,638   -     22,638 Total operating expenses   78,031   (1,460 )   76,571   Operating income (loss) 21,381 1,460 22,841 Other income (expenses) 15 - 15 Income (loss) from equity method investments   2,865   -     2,865 Income (loss) before income taxes 24,261 1,460 25,721 Provision for income taxes   4,300   5,988   (b)   10,288 Net income (loss) 19,961 (4,528 ) 15,433   Net income (loss) attributable to noncontrolling interests   14,625   (14,625 )   - Net income (loss) attributable to Moelis & Company $ 5,336 $ 10,097   $ 15,433   Weighted-average shares of Class A commonstock outstanding 

Basic   19,730,182   34,407,005   (b)   54,137,187 Diluted   20,948,966   34,407,005   (b)   55,355,971 Net income (loss) attributable to holders of shares of Class Acommon stock per share 

Basic $ 0.27 $ 0.29 Diluted $ 0.25 $ 0.28   (a)   Expense associated with the amortization of RSUs and stock options granted in connection with the IPO. In accordance with GAAP, amortization expense of RSUs and stock options granted in connection with the IPO will be recognized over the five year vesting period; we will continue to adjust for this expense due to the one-time nature of the grant.   (b) Assumes all outstanding Class A partnership units have been exchanged into Class A common stock. Accordingly, an adjustment has been made such that 100% of the Firm’s income is taxed at the corporate effective tax rate of 40.0% for the period presented. View source version on businesswire.com: http://www.businesswire.com/news/home/20160427006651/en/

Investor:Moelis & CompanyMichele Miyakawat: + 1 310 443 2344michele.miyakawa@moelis.comorMedia:Moelis & CompanyAndrea Hurstt: + 1 212 883 3666m: +1 347 583 9705andrea.hurst@moelis.com

Source: Moelis & Company

**Comment by DharmeshRana** [comment]
Fixed
