### ISSUE TITLE
Corp Overview - Sidebar responsiveness

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#6]
This occurs on the "tablet" breakpoint. Approx (750-1k px width).

Fixing that embed code (#4) should get that out of the menu, but should the arrow move on top?

![corporate_overview_ticker](https://cloud.githubusercontent.com/assets/18052292/14888172/f19256aa-0d26-11e6-9a47-8c2634f2f4c2.png)

**Comment by esea48** [comment]
@stevenaquinn -  recheck now.

**Comment by stevenaquinn** [comment]
This issue is fixed! Closing ticket, Thank you!
