### ISSUE TITLE
Stock Information - Drawers acting as Hover state

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#8]
On the stock information page chart, we have 2 sets of drawers, with drawers within.  Initial drawers operate fine, but the internal drawers are acting as hover states, making it incredibly frustrating to navigate the options. Indexes, Events, Performance Metrics, Chart Type and Tracker type should act as drawers.

![stock_information_hover_state](https://cloud.githubusercontent.com/assets/18052292/14888627/43e24f1c-0d29-11e6-9d2b-8a0c01a6c760.gif)

**Comment by stevenaquinn** [comment]
This issue is fixed, but we have another functionality issue here. The viewports for the drawers extend too far, making them hard to close/ hard to select update, etc. They are closing via hovering outside of the drawer, which is fine by me, but if that the case we need to make the viewport much tighter.

## ![stock_information_drawers_viewports](https://cloud.githubusercontent.com/assets/18052292/15409116/6ab811c6-1de1-11e6-8b1d-553a18dd71a1.png)

![stock_information_drawers_functionality](https://cloud.githubusercontent.com/assets/18052292/15406359/316304d8-1dd4-11e6-879c-e910631a48f3.gif)

**Comment by DharmeshRana** [comment]
This is working fine for me. Kindly review.
