### ISSUE TITLE
Stock Information - Add Comparison Tickers

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#9]
When you select add comparison tickers, the copy inside the text box "ADD COMPARISON TICKERS" doesn't disappear when selected, until you start typing in the text box.  Do we want the copy to disappear as soon as selected? Initially I was unsure whether or not I had selected it.

![stock_information_comparison_tickers](https://cloud.githubusercontent.com/assets/18052292/14888769/d2b53da8-0d29-11e6-84bf-6c4274c8a2cb.gif)

**Comment by DharmeshRana** [comment]
I think the comment makes sense. I have forwarded to designer to fix.

**Comment by DharmeshRana** [comment]
Fixed - https://www.snl.com/IRW/Stock/4363272/preview
